### ISSUE TITLE
Detecting ramen resources per application

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1046]
Current system does not have uniform way to find all the relevant ramen resources for specific application.

The system makes it very hard to locate all the resources without known the resource kind (e.g. `kubectl get all -n namespace` return only some kinds).

### One application per namespace - subscriptions/rbd

```
hub:
  app-namespace:
    drpc:
      name: app-name-placement-1-drpc
cluster1:
  app-namespace:
    vrg:
      name: app-name-placement-1-drpc
    vrs:
    - name: pvc-name
cluster1:
  app-namespace:
```

### One application per namespace - applicationset/rbd

```
hub:
  openshift-gitops:
    drpc:
      name: app-name-placement-drpc
cluster1:
  app-namespace:
    vrg:
      name: app-name-placement-drpc
    vrs:
    - name: pvc-name
cluster1:
  app-namespace:
```

### One application per namespace - applicationset/cephfs

```
hub:
  openshift-gitops:
    drpc:
      name: app-name-placement-drpc
cluster1:
  app-namespace:
    vrg:
      name: app-name-placement-drpc
    replicationsources:
    - name: pvc-name?
cluster1:
  app-namespace:
    vrg:
      name: app-name-placement-drpc
    replicationdestinations:
    - name: pvc-name?```
```

### Multiple application per namespace

(Not sure how this looks, if you do please update this section)

### One application, multiple namespaces

(Not sure how this will look, @hatfieldbrian may add more info on this)

### Locating stuff

- drpc
  - Depends on application implementation (subscription/application sets)
  - Depend on undocumented drpc name format that may change in future versions
- vrg
  - Depend on drpc name format, again implementation detail that can change in future versions
- vr/replicaiton{source,destination}
  - Depend on the pvc name, need to know the specific deployment

## Suggested solution

When users create applications in ACM, they must create an application name and use it to
locate the application and perform actions.

Users also create an application namespace, not sure if we can use the same namespace to have multiple applications in the same namespace.

When the application is create from the UI, all resources related to the application can have the same label common label:

```yaml
labels:
  app.kubernetes.io/name: mysql
```

This can be applied to:
- subscription
- placement
- applicationset
- drpc
- vrg (ramen can propagate the label from the drpc)
- vr (ramen can propagate the label from the vrg)
- replication{source,destination}? (ramen can propagate the label from drpc/vrg)
- manifestwork?
- namespaces?
- application resources?

With this tools (like ramen kubectl plugin) can identify an application using:

    kubectl ramen status --namespace xxx --app-name yyy

Or using kubectl:

    kubectl get --selector app.kubernetes.io/name=yyy

Tools can deal with the difference between subscriptions and applications sets by looking the application namespace and gitops namespace on the hub.

## Issues

- subscription/placement/applicationset label - depends on OCM/ACM?
- maybe we can add the label when assigning drpolicy to an application?

## See also

- https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
