### ISSUE TITLE
e2e: Improve storage class names and supported storage checks

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1635]
The e2e framework uses a list of storage class names and access modes:

```yaml
pvcspecs:
  - storageclassname: rook-cephfs
    accessmodes: ReadWriteMany
  - storageclassname: rook-ceph-block
    accessmodes: ReadWriteOnce
```

Based on this list, we generate test names:

```go
func generateSuffix(storageClassName string) string {
	suffix := storageClassName

	if strings.ToLower(storageClassName) == "rook-ceph-block" {
		suffix = "rbd"
	}

	if strings.ToLower(storageClassName) == "rook-cephfs" {
		suffix = "cephfs"
	}

	return suffix
}
```

This works only for drenv environment. For openshift environment the storage class names are different so the returned suffix with be the actual storage class name, which is way to long to use as a test name or for using resource names.

Even worse, there is code hidden deployers/discoveredapps.go, filtering out cephfs workloads for discovered apps, based on the suffix:

```go
func (d DiscoveredApps) IsWorkloadSupported(w workloads.Workload) bool {
	return w.GetName() != "Deploy-cephfs"
}
```

This will not match for when using real cluster storage classes, trying to run unsupported combination.

## Possible fix

Move the logic to the config:

```
storage:
  - name: file
    storageclassname: rook-cephfs
    accessmodes: ReadWriteMany
    supports-discovered-apps: false
  - name: block
    storageclassname: rook-ceph-block
    accessmodes: ReadWriteOnce
    supports-discovered-apps: true
```

- With this layout we can define any storage class and enable the storage class for discovered apps without changing the code. 
- We don't need the code mapping the actual storage class names to test names, instead we can use the name property.

Blocks #1625
