### ISSUE TITLE
e2e: Improve config.yaml

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1771]
Make more things configurable, so we can run the tests on any cluster.

Group related stuff to make names shorter and nicer to work with, and allow code to work with simple types holding the config sections.

This make it impossible to use env vars for configs, but this is a good thing.
 
Blocks ##1716

## Combine channel options and improve the default names

Make it easier for the code by using a ctx.Config().Chanel.Name and ctx.Config.Channel().Namespace

```yaml
channel:
  name: channel
  namespace: e2e-gitops
```
## Move repo related constants to config, gathered under repo

Make it easier for the code to use ctx.Config().Repo.Url and ctx.Config().Repo.Branch.

```yaml
repo:
  url: {ocm-ramen-samples url}
  branch: main
```

## Add clusterset option

On drenv we have "default", on ocp cluster ti can be anything the admin creates.

```yaml
  clusterSet: default
```

Issues:
- This can be also an option on the hub cluster in the clusters section, but using generic cluster type is nice
- Do we have other OCM related configs?

## Move ramen namespaces to config

We need to support different namespaces on k8s and ocp:
- ramenNamespace to ramenHubNamespace (ramen-system on k8s, openshift-operators on ocp),
- ramenClusterNamespace (ramen-system on k8s, openshift-dr-system on ocp)
- ramenOpsNamespace (ramen-ops on k8s, openshift-dr-ops on ocp)

Move the ramen namespace constants to the config so we can run on any cluster 

```yaml
ramen:
  hubNamespace: ramen-system
  clusterNamespace: ramen-system
  opsNamspace: ramen-ops
```

Issues:
- Do we have other namespaces?
- Do we want more generic "namespaces" option?

## Add drPolicy config

We need to support different dr-policy names:
- "dr-policy" on drenv
- anything the user creates on ocp

```yaml
drPolicy: dr-policy
```

Issues:
- Combine with ramen option? this is admin choice, not platform choice, more likely to change, ramen namespaces will never change
