### ISSUE TITLE
e2e: Change placement creation to select specific cluster instead of random selection

### ISSUE THREAD

**Issue by parikshithb** [RamenDR/ramen#1851]
The current placement [implementation](https://github.com/RamenDR/ramen/blob/main/e2e/deployers/crud.go#L90) creates a placement without specifying a particular cluster, this results in random cluster selection within the cluster set. This behavior can be improved by explicitly specifying the cluster name where the workload should be deployed.

Advantages:
1.  Closer to real-world usage, one cluster is designated as the primary, rather than selecting randomly.
2. Helps with consistency and easier debugging.
3. Aligns upstream testing with downstream workflows, making it more useful.

Tasks:
Instead of selecting a random cluster, the placement should be created using the first cluster retrieved from getDRPolicy and added to requiredClusterSelector. The placement should follow this format:

```
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement
spec:
  clusterSets:
    - default
  numberOfClusters: 1
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: name
          operator: In
          values:
          - dr1
 ```
