### ISSUE TITLE
Enhancing resource conflict handling to ensure seamless failover and relocation.

### ISSUE THREAD

**Issue by GowthamShanmugam** [RamenDR/ramen#1861]
**1. PersistentVolumeClaim (PVC) Conflict Check**

**1.1 PVC Conflict Check on the Primary Cluster**

**Current Implementation:** Already implemented.

**Purpose:** Primary PVCs act as the source for data replication. A single PVC should not be protected by multiple VolumeReplicationGroups (VRGs), as this could result in redundant data replication, leading to wasted resources.

**Conflict Resolution Mechanism:**
* Ramen resolves this by adding an annotation to each PVC:
```
ramendr.openshift.io/owner-name={vrg-name}
```
* If a PVC already has this annotation, it means another VRG is protecting it. In such cases, any additional attempt to protect the same PVC will fail, preventing duplication.
        
**1.2 PVC Conflict Check on the Secondary Cluster**
**Current Status:** Not yet implemented.

**Purpose:** To prevent unintentional PVC protection after a failover or relocation.
* The PVC label selector may not always match the same PVCs on the failover/relocated cluster as it did on the primary.
* This could lead to selecting a PVC that belongs to a different application workload.
* While the primary cluster’s conflict check (1.1) will eventually catch this issue, it happens too late. The goal is to detect conflicts as early as possible.

**Example Scenario: PVC Label Selector Conflict**
**Primary Cluster (Cluster 1)**
PVC:
```
name: app-pvc-1
labels:
  app: backup-service
  volume-type: SSD
```
VRG1 (Primary for VolumeReplicationGroup of Cluster 1):
```
pvcLabelSelector:
  matchExpressions:
    - key: "volume-type"
      operator: "In"
      values: ["SSD"]
```
This configuration ensures that any PVC with volume-type=ssd is selected.

**Secondary Cluster (Cluster 2)**
PVCs:
```
name: app-pvc-2
labels:
  app: mysql
  volume-type: ssd
```

**Unintended PVC Selection:**
* After failover/relocate, VRG1's label selector might select both app-pvc-1 and app-pvc-2.
* However, app-pvc-2 does not belong to backup-service, leading to unintended protection of an unrelated PVC.
By implementing an early conflict check on the secondary cluster, we can prevent such issues before they impact the workload.

2. K8s resource conflict check(Only for discovered)

**Comment by GowthamShanmugam** [comment]
cc: @nirs @BenamarMk @ShyamsundarR @raghavendra-talur

**Comment by nirs** [comment]
@GowthamShanmugam thanks for making the issue clear.

The problem is very clear now - pvc on secondary cluster in the same namespace, matching the pvc selector. We have a case like this when testing kubevirt, when a leftover pvc from previous test broke failover. Warning about such pvcs early is important.

The example label used (volume-type: ssd) is a very bad selector for dr and should never be used. Label selector should match only application specific pvcs.

How do you plan to resolve the conflict?

- log in ramen on the secondary cluster - easy but not very helpful
- propagate the conflicting pvcs to the drpc?
- issue alerts so the console will show this issue immediately when found?
- label/annotate the pvc to avoid conflict? if we can detect conflict, we can mark the pvc as conflicting, which will avoid selecting it later. The label can be removed when disabling dr.

**Comment by GowthamShanmugam** [comment]
> How do you plan to resolve the conflict?
Here’s a clearer and more detailed version of your message:

---

### How do you plan to resolve the conflict?  

I have raised a PR to detect conflicts within the secondary VRG (VolumeReplicationGroup) reconciler. As part of this solution, I am updating the VRG status by setting the **DataProtected** condition accordingly.  

For **VolSync**, the current status is:  
```yaml
- lastTransitionTime: '2025-02-28T11:05:28Z'
  message: A PVC that is not a replication destination should not match the label selector.
  observedGeneration: 8
  reason: PVCConflict
  status: 'False'  # Should this be False or True?
  type: DataProtected
```

For **VolumeReplication (VolRep)**, the status is:  
```yaml
- lastTransitionTime: '2025-02-28T10:18:20Z'
  message: No PVC on the secondary should match the label selector.
  observedGeneration: 3
  reason: PVCConflict
  status: 'False'  # Should this be False or True?
  type: DataProtected
```

Now, I want to update the **DRPC (Disaster Recovery Placement Control)** condition based on the **DataProtected** condition in the secondary VRG. However, I am not sure about the correct approach for this.  

The key concern is ensuring that this update does not disrupt the **existing replication process**. One possible solution could be updating the **DRPC PeerReady** condition to **False**, thereby blocking the failover in case of a conflict. Would this approach be appropriate? I need guidance on how to implement this correctly while preserving the current replication functionality.  

---

How to display this conflict in UI has not yet been decided; I will work with UX to figure that out.
