### ISSUE TITLE
e2e: Discover managed cluster names automatically

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1866]
In #1863 we are adding configuration as a quick way to get good logging. This is trivial to do with drenv since we control the environment file and the dr-policy. For real cluster the user running e2e or ramenctl will have to configure the clusters names correctly.

## Issues

We have several possible issues:
- Adding the clusters in different order
- Names do not match the clusters
- Wrong kubeconfig

### Clusters order

It is easy to configure the clusters in a different order than the dr-policy.

config.yaml:

```yaml
clusters:
  hub:
    name: hub
    kubeconfigpath: kubeconfigs/hub
  c1:
    name: bar
    kubeconfigpath: kubeconfigs/bar
  c2:
    name: foo
    kubeconfigpath: kubeconfigs/foo
```

dr-policy:

```yaml
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  name: dr-policy
spec:
  drClusters:
  - foo
  - bar
  schedulingInterval: 1m
  replicationClassSelector: {}
  volumeSnapshotClassSelector: {}
```

### Name mismatch

Even if the cluster are in the same order, they may not match the kubeconfigs:

config.yaml:

```yaml
clusters:
  hub:
    name: hub
    kubeconfigpath: kubeconfigs/hub
  c1:
    name: foo
    kubeconfigpath: kubeconfigs/bar
  c2:
    name: bar
    kubeconfigpath: kubeconfigs/foo
```

### Wrong kubeconfig

```yaml
clusters:
  hub:
    name: hub
    kubeconfigpath: kubeconfigs/hub
  c1:
    name: foo
    kubeconfigpath: kubeconfigs/foo
  c2:
    name: bar
    kubeconfigpath: kubeconfigs/oops
```

### Startup

Don't document the cluster name, so this option is used only for testing environment when we control the config.

Use the name "hub" for the hub, this is a good default, and user can override it in the config if needed.

For managed clusters, when we set up the client, get the "clusterclaims/name" resource from the cluster:

```console
% kubectl --kubeconfig ~/.config/drenv/rdr/kubeconfigs/dr1 get clusterclaims/name -o jsonpath='{.spec.value}{"\n"}'
dr1
% kubectl --kubeconfig ~/.config/drenv/rdr/kubeconfigs/dr2 get clusterclaims/name -o jsonpath='{.spec.value}{"\n"}'
dr2
                                                                                                                                 
```

And set the cluster name.

When we need to match the dr-policy drclusters to c1, c2, use the cluster name and not the order, so it does not matter how we set the clusters.

## Validate config

When validating the config check that drpolicy's drclusters matches the clusters in the config. If they don't match we may have wrong drpolicy or wrong kubeconfig.
