### ISSUE TITLE
Panic observed when tried protecting PV not provisioned by RBD or CEPHFS(provisioned from default storage class)

### ISSUE THREAD

**Issue by pruthvitd** [RamenDR/ramen#1888]
Panic observed in drplacementcontrol.go for not finding a matching StorageClassName in drpolicy.

A validation check should be added to handle DR protection of application with out PVs.

Recreation Steps:
1. Create app with a PVC attached.
2. Attached PV is not provisioned by RBD or CEPHFS. 
3. PV is provisioned by default storageclass - Standard(default)
4. Create drpc for the app, which creates manifestwork, vrg on managed clusters.
5. DRPC instance reports the unsupported storage ID: 
```
Failed to process list of PVCs to protect: label (ramendr.openshift.io/storageid)
        not found in storageClass for PVC fedora'
```

Also panic is reported in the log.
```
2025-03-05T11:18:14.725Z	ERROR	runtime/signal_unix.go:881	Observed a panic	{"controller": "drplacementcontrol", "controllerGroup": "ramendr.openshift.io", "controllerKind": "DRPlacementControl", "DRPlacementControl": {"name":"test-dr","namespace":"ramen-ops"}, "namespace": "ramen-ops", "name": "test-dr", "reconcileID": "a4eebec5-088a-4235-9661-de29a0c4882b", "panic": "runtime error: invalid memory address or nil pointer dereference", "panicGoValue": "\"invalid memory address or nil pointer dereference\"", "stacktrace": "goroutine 322 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x271d538, 0xc000a800f0}, {0x1d3e3a0, 0x37d0630})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.31.2/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:105 +0x114\npanic({0x1d3e3a0?, 0x37d0630?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngithub.com/ramendr/ramen/internal/controller.updatePeers(0xc000f93d48, {0xc0004cd400, 0x2, 0x0?}, {0xc0004ccc80, 0x2, 0x0?})\n\t/workspace/internal/controller/drplacementcontrol.go:1600 +0xe6\ngithub.com/ramendr/ramen/internal/controller.(*DRPCInstance).updateVRGAsyncSpec(0xc0007186c8, 0xc000f93d48, 0xc000718908)\n\t/workspace/internal/controller/drplacementcontrol.go:1643 +0x26c\ngithub.com/ramendr/ramen/internal/controller.(*DRPCInstance).updateVRGDRTypeSpec(0xc000604008?, 0x2?, 0x2096d66?)\n\t/workspace/internal/controller/drplacementcontrol.go:1694 +0x4e\ngithub.com/ramendr/ramen/internal/controller.(*DRPCInstance).updateVRGOptionalFields(0xc0007186c8, 0xc000718908, 0xc000f93d48, {0xc0011b8999, 0x3})\n\t/workspace/internal/controller/drplacementcontrol.go:1734 +0x654\ngithub.com/ramendr/ramen/internal/controller.(*DRPCInstance).ensureVRGManifestWork(0xc0007186c8, {0xc0011b8999, 0x3})\n\t/workspace/internal/controller/drplacementcontrol.go:1571 +0x3fb\ngithub.com/ramendr/ramen/internal/controller.(*DRPCInstance).RunInitialDeployment(0xc0007186c8)\n\t/workspace/internal/controller/drplacementcontrol.go:173 +0x63a\ngithub.com/ramendr/ramen/internal/controller.(*DRPCInstance).processPlacement(0xc0007186c8)\n\t/workspace/internal/controller/drplacementcontrol.go:119 +0x112\ngithub.com/ramendr/ramen/internal/controller.(*DRPCInstance).startProcessing(0xc0007186c8)\n\t/workspace/internal/controller/drplacementcontrol.go:81 +0x58\ngithub.com/ramendr/ramen/internal/controller.(*DRPlacementControlReconciler).reconcileDRPCInstance(0xc000618ea0, 0xc0007186c8, {{0x2721fb8?, 0xc000a80120?}, 0x271d538?})\n\t/workspace/internal/controller/drplacementcontrol_controller.go:477 +0x13e\ngithub.com/ramendr/ramen/internal/controller.(*DRPlacementControlReconciler).Reconcile(0xc000618ea0, {0x271d538, 0xc000a800f0}, {{{0xc0006faa47, 0x9}, {0xc0006faa40, 0x7}}})\n\t/workspace/internal/controller/drplacementcontrol_controller.go:241 +0xe45\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc000a80060?, {0x271d538?, 0xc000a800f0?}, {{{0xc0006faa47?, 0x0?}, {0xc0006faa40?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:116 +0xd4\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x272dde0, {0x271d570, 0xc00071a7d0}, {{{0xc0006faa47, 0x9}, {0xc0006faa40, 0x7}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:303 +0x3b8\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x272dde0, {0x271d570, 0xc00071a7d0})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263 +0x23f\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224 +0x8a\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 83\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:220 +0x490\n"}
2025-03-05T11:18:14.725Z	ERROR	controller/controller.go:316	Reconciler error	{"controller": "drplacementcontrol", "controllerGroup": "ramendr.openshift.io", "controllerKind": "DRPlacementControl", "DRPlacementControl": {"name":"test-dr","namespace":"ramen-ops"}, "namespace": "ramen-ops", "name": "test-dr", "reconcileID": "a4eebec5-088a-4235-9661-de29a0c4882b", "error": "panic: runtime error: invalid memory address or nil pointer dereference [recovered]"}
```

**Comment by pruthvitd** [comment]
### DRPolicy:

```
status:
  async:
    peerClasses:
    - clusterIDs:
      - eaee4dd8-8ff3-4738-b60e-fd584ad25b2f
      - d465d043-d60d-4e4b-a8fd-fac7ddee5037
      replicationID: rook-ceph-replication-1
      storageClassName: rook-ceph-block
      storageID:
      - rook-ceph-block-dr1-1
      - rook-ceph-block-dr2-1
    - clusterIDs:
      - eaee4dd8-8ff3-4738-b60e-fd584ad25b2f
      - d465d043-d60d-4e4b-a8fd-fac7ddee5037
      storageClassName: rook-cephfs-test-fs1
      storageID:
      - rook-cephfs-test-fs1-dr1-1
      - rook-cephfs-test-fs1-dr2-1
  conditions:
  - lastTransitionTime: "2025-02-27T18:04:54Z"
    message: drpolicy validated
    observedGeneration: 2
    reason: Succeeded
    status: "True"
    type: Validated
```

### PVC
```
# oc get pvc fedora -n kubevirt-test --context dr1
NAME     STATUS   VOLUME                                     CAPACITY     ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
fedora   Bound    pvc-49cb1c34-651b-4a3b-b474-190a1f431a86   5681173672   RWO            standard       <unset>                 5d8h
```

### protectedPVCs from VRG
```
  protectedPVCs:
  - conditions:
    - lastTransitionTime: "2025-02-28T18:11:36Z"
      message: peerClass matching storageClass standard not found for PVC
      observedGeneration: 2
      reason: PeerClassNotFound
      status: Unknown
      type: DataReady
    name: fedora
    namespace: kubevirt-test
    replicationID:
      id: ""
    resources: {}
    storageID:
      id: ""
  state: Primary
```

### DRPC Status
```
status:
  actionStartTime: "2025-03-04T12:43:23Z"
  conditions:
  - lastTransitionTime: "2025-02-28T12:44:28Z"
    message: Initial deployment completed
    observedGeneration: 2
    reason: Deployed
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-28T12:44:28Z"
    message: Ready
    observedGeneration: 2
    reason: Success
    status: "True"
    type: PeerReady
  - lastTransitionTime: "2025-02-28T17:37:36Z"
    message: VolumeReplicationGroup (ramen-ops/test-dr) on cluster dr1 is not reporting
      any status about workload resources readiness, retrying till ClusterDataReady
      condition is met
    observedGeneration: 2
    reason: Unknown
    status: Unknown
    type: Protected
  lastKubeObjectProtectionTime: "2025-02-28T17:34:51Z"
  lastUpdateTime: "2025-03-04T12:43:23Z"
  observedGeneration: 2
  phase: Deployed
  preferredDecision:
    clusterName: dr1
    clusterNamespace: dr1
  progression: UpdatingPlRule
  resourceConditions:
    conditions:
    - lastTransitionTime: "2025-02-28T17:37:31Z"
      message: 'Failed to process list of PVCs to protect: label (ramendr.openshift.io/storageid)
        not found in storageClass for PVC fedora'
      observedGeneration: 2
      reason: Error
      status: "False"
      type: DataReady
```
