### ISSUE TITLE
e2e: validate user provided cluster name with clusters in drpolicy

### ISSUE THREAD

**Issue by parikshithb** [RamenDR/ramen#1937]
Currently there is no validation to confirm that dr cluster names provided by user exists in the drpolicy. Need to add a validation to verify dr clusters exists in drpolicy.

```
 c1:
   name: dr1
   kubeconfig: dr1/config
 c2:
   name: dr2
   kubeconfig: dr2/config
```
