### ISSUE TITLE
e2e: Support test skipping

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1966]
We can control which tests are running by adding and removing tests from the config file, but this is too much work and error prone. We can add a "skip" property to skip tests:

```yaml
tests:
- workload: foo
  deployer: bar
  pvcspec: baz
  skip: true
```

We plan to use this for recipes tests, when we may have large number of tests that should be easy to run when needed, but we don't want to run all of them for every pr.
