### ISSUE TITLE
e2e: Test tags

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1967]
We want to add many new tests that may not need to run for every pr, but we may want to run all the tests periodically (e.g. daily, weekly, ...). One way to do this is to add tags to the tests:

```yaml
tests:
- deployer: appset
  workload: deploy
  pvcspec: rbd
  tags: [pr, keekly]
- deployer: disapp
  workload: vm
  pvcspec: rbd
  tags: [vms, weekly]
```

The e2e test can add --tags for selecting tests based on tags.

The e2e job can use:

    ./ramen-e2e --tags pr

A weekly job can use:

    ./ramen-e2e --tags weekly

A developer can run only vms tests using:

    ./ramen-e2e --tags vms
