### ISSUE TITLE
e2e: Fail e2e job if user is not allowed to run the e2e job

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1994]
Currently we skip the job, so the job looks ready to merge - when e2e did not run!

Example PR that *did not run e2e job*:

![Image](https://github.com/user-attachments/assets/0cba80ad-cb5e-425f-8984-45873cf27f79)

This makes it too easy to merge a broken change without testing it.

Caused by using:

```yaml
jobs:
  e2e-rdr:
    runs-on: [self-hosted, e2e-rdr]
    if: github.repository == 'RamenDR/ramen' && github.event.pull_request.author_association == 'MEMBER'                                   
```

What we should do:
- Run a script checking permissions and fail the job with clear error message

Issues:
- With the current check, there is no way to pass e2e job if you are not an org member. We need another check to override this maybe having a `ok to test` label or comment from maintainer with `/ok-to-test`.
