### ISSUE TITLE
VRG ManifestWork fails to be created if workload namespace is not present on the managed cluster

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#240]
Till now the workload testing has involved creating the namespace on all managed clusters as it carried the S3 secret. Thus when creating VRG MW first to restore PVs to a managed cluster it was succeeding to create the same.

Post moving S3 configuration to the controller configuration and hence moving the secrets from the workload namespace to the ramen controller namespace, this initial VRG creation fails as the namespace in which to create it is missing on the target cluster.

Error observed in MW work status (for VRG):
```
    - conditions:
      - lastTransitionTime: "2021-08-24T11:21:00Z"
        message: 'Failed to apply manifest: namespaces "busybox-sample" not found'
        reason: AppliedManifestFailed
        status: "False"
        type: Applied
```

**Comment by ShyamsundarR** [comment]
A simple addition of a manifest work to create the ns alongwith the initial deployment to a cluster helps, the caveats though are,
- OCM does not delete the ns when a subscription moves between clusters
- MW would be deleted in the end where the workload also gets deleted but there maybe other Subscriptions/workloads using the same namespace, so deleting it is not advisable
- Any changes to the ns based on OCM deployable/subscription should not get overwritten by the MW that we create (like the PV MW issue that we faced)

Overall MW for ns does not seem like a good option, unless we have the one-shot MW semantics for the same to avoid any future changes getting overwritten by the MW and also to delete the MW for ns without any repercussion on the managed cluster.

Sample MW looks like so:
```
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: testns1-ns-mw
  namespace: east
spec:
  workload:
    manifests:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: testns1
```
