### ISSUE TITLE
Add one more condition to DRPC stating VRG is "Ready" on current cluster?

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#294]
Currently DRPC conditions are as follows (edited):
```
  status:
    conditions:
    - status: "True"
      type: Available
    - status: "True"
      type: PeersReady
```

`Available` becomes true once a manifest work for VRG with the desired state is created on the desired cluster.

There are times where the cluster has not yet caught up to the desired state, or there are volume promotion failures etc. These are in the `resourceConditions` but overall does not have a context in DRPC.

The ask is to hence to see how best to reflect the same in DRPC as well, possibly a `Ready` condition once VRG reports readiness on the cluster?
