### ISSUE TITLE
Support templates in test environment yaml

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#632]
The current format is very simple to understand, what you see is what you get. If you want
2 identical clusters with different names (dr1, dr2), you have to create 2 identical clusters.

We can make this easier with templates, for example:

```yaml
templates:
  - name: dr-cluster
    memory: 6g
    network: default
    scripts:
      - cert-manager
      - olm
      - rook
      - ocm-cluster
 - name: hub
   memory: 4g
   network: default
   scripts:
     - cert-manager
     - olm
     - ocm-hub
  
profiles:
  - name: dr1
    template: dr-cluster
  - name: dr2
    template: dr-cluster
  - name: hub
    template: hub
```

The implementation can be trivial:

```
>>> profile = {"name": "dr1", "template": "dr-cluster"}
>>> dr_cluster = {"name": "dr-cluster", "memory": "6g"}
>>> profile = collections.ChainMap(profile, dr_cluster)
>>> profile
ChainMap({'name': 'dr1', 'template': 'dr-cluster'}, {'name': 'dr-cluster', 'memory': '6g'})
>>> profile["name"]
'dr1'
>>> profile["memory"]
'6g'
```

**Comment by nirs** [comment]
@ShyamsundarR what do you think?

**Comment by ShyamsundarR** [comment]
This is useful in writing concise env definitions (than repeating and causing cut/paste issues across clusters).

We do use a 2 cluster footprint as well, where the hub is a ManagedCluster as well, will this adapt to the same?

**Comment by nirs** [comment]
I did try to create a hub which is also a managed cluster since this sounds like wrong
approach for production.

If we do need to do this because we cannot run 3 clusters in very small environment
(e.g. github ci), I think we can do this like this, no templates are needed:

```yaml
profiles:
  - name: dr1
    memory: 6g
    network: default
    scripts:
      - cert-manager
      - olm
      - rook
      - ocm-cluster
 - name: 2
   memory: 8g
   network: default
   scripts:
     - cert-manager
     - olm
     - ocm-hub
     - olm
     - rook
     - ocm-cluster
```

We can also support mixing values from multiple templates, but this stats to become 
complicated to understand the semantics. It think we should try to keep the format
simple.
