### ISSUE TITLE
More generic and flexible test environment yaml format

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#633]
Current test environment yaml format specify a path to the start and or test scripts:

```
scripts:
  - file: foo/start
  - file: bar/start
    args: ["1"]
  - file: bar/test
    args: ["1"]
```

This is too verbose and not flexible enough.

We want:
- less verbose
- no boilerplate
- support disabling or enabling tests per run
- support builtin scripts so people do not have to write the same scripts again
- support scripts running during stop and delete

## New format

```yamls
addons:
  - name: foo
  - name: bar
    args: ["1"]
```

Assuming that we have `foo/start`, `bar/start`, `bar/test`, starting
will:

- run `foo/start`
- run `bar/start 1`
- run `bar/test 1`

If we don't have `bar` directory, lookup builtin addon named bar
and it run its `bar.start()` and `bar.test()` function.

When stopping, look for `foo/stop`, `bar/stop` and run them. If the directory
is missing, look up builtin addons and run their `addon.stop()` function.

When deleting, do the same for `delete` script or builtin addon function.
