### ISSUE TITLE
drenv isolation between different enviroments

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#637]
Developer or CI may want to run multiple environments at the same time.
This is not possible now since environments uses the same profile names
(e.g. hub, dr1, dr2).

Using same names for profiles is good, it makes it easy to work with
different environments, so we don't want to change this.

### Developer workflow

Developer testing one environment (e.g. ocm.yaml) while another environment is running (e.g. regional-dr). This is very useful since starting full regional dr takes about 320-480 seconds but starting ocm takes about 200 seconds.

### CI

CI running multiple environments on the same host or vm, one per PR. We can avoid this by using separate VM per PR job, but this may mean multiple levels of nested virtualization which may not be supported or not work well.

## Plan

Add a prefix for every environment:

```yaml
prefix: rdr
profiles:
  - name: "dr1"
    ...
```

The minikube instance can be named `rdr-dr1`.

Add a `--prefix` option to drenv:

```
drenv start --prefix test regional-dr.yaml
```

The minikube instance will be created as `test-dr1`.

When running tests locally, we can use `--prefix test`.
In CI environment we can use a random prefix, or the build id.

**Comment by nirs** [comment]
After working on #632, I'm not sure abut using prefix in the yaml. It is easy to 
have unique names in the actual yamls to allow concurrent use of different envs.

Example regional-dr.yaml:

```yaml
profiles:
  - name: rdr-dr1
  - name: rdr-dr2
  - name: rdr-hub
```
Example metro-dr.yaml:
```
profiles:
  - name: mdr-dr1
  - name: mdr-dr2
  - name: mdr-hub
```

The `--prefix` option is probably the only thing we need for isolation. This will
allow running multiple instances of the same env.

**Comment by nirs** [comment]
Adding prefix is easy to env.name and profile.name. If done first, it will fix profile names and worker names, and use of $name.

We have an issue with user arguments like:

```yaml
- profiles:
  - name: "dr1"
    workers:
    - scripts
      - file: ocm-cluster/start
        args: ["$name", "hub"]
workers:
- scripts:
  - file: rbd-mirror/start
    args: ["dr1", "dr2"]
```

If we prefix "hub" in ocm-cluster, or "dr1", "dr2" in rbd-mirror, we risk braking future scripts using argument which is not a cluster name.


## Possible solutions

### Add special variable $prefix:

```yaml
- profiles:
  - name: "${prefix}dr1"
    workers:
    - scripts
      - file: ocm-cluster/start
        args: ["${prefix}${name}", "${prefix}hub"]
  - name: "${prefix}dr2"
  - name: "${prefix}hub"
workers:
- scripts:
  - file: rbd-mirror/start
    args: ["${prefix}dr1", "${prefix}dr2"]
```

Trivial to implement, harder to use.


### Add a way to refer to cluster name instead of duplicating the value:

```yaml
- profiles:
  - name: "dr1"
    workers:
    - scripts
      - file: ocm-cluster/start
        args: ["$name", "$profile.2.name"]
  - name: "dr2"
  - name: "hub"
workers:
- scripts:
  - file: rbd-mirror/start
    args: ["$profile.0.name", "$profile.1.name"]
```

Complicated to implement, complicated to use.

### Unify arguments to all scripts

All scripts will get all the names and use what they need.
Scripts need to know the current cluster.

Not sure how this can be in a generic way.
