### ISSUE TITLE
Support VRG format with the `async` and `sync` `mode` fields (prior to PR #432)

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ramen#730]
# Problem
Fusion went GA with the mode fields.  To move to the latest Ramen level, support is needed for existing VRGs with the `async` or `sync` enablement through `mode` fields.

# Solution approaches
## Approach 1: Migrate on demand
On each reconcile, check its version, if `v1alpha1`, then migrate to new `v1alpha2`
## Approach 2: Migrate non-concurrently as part of upgrade
When VRG controller is shutdown for upgrade, a tool converts all VRGs to latest level, then VRG controller can be restarted

**Comment by ShyamsundarR** [comment]
Here is a minikube test that I did with the older and newer VRG CRDs retaining the same API version, and it works as expected, But needs a manual switch over for users that have VRG CRs from the older to the newer CRD:

```
# Get Shio version of VRG CRD
wget https://raw.githubusercontent.com/RamenDR/ShioRamen/main/config/crd/bases/ramendr.openshift.io_volumereplicationgroups.yaml
mv ./ramendr.openshift.io_volumereplicationgroups.yaml ./ramendr.openshift.io_volumereplicationgroups-shio.yaml 

# Get upstream current ramen version of VRG CRD
wget https://raw.githubusercontent.com/RamenDR/ramen/main/config/crd/bases/ramendr.openshift.io_volumereplicationgroups.yaml

# Start with Shio version of CRD in API server
kubectl apply -f ./ramendr.openshift.io_volumereplicationgroups-shio.yaml

# Create a Shio-version VRG resource
kubectl apply -f ./vrg-fusion24.yaml 
kubectl get vrg -A -o yaml

# Upgrade the CRD version to upstream ramen
kubectl apply -f ./ramendr.openshift.io_volumereplicationgroups.yaml

# Fetch existing resource; Success
kubectl get vrg -A -o yaml

# Create a new new VRG as per current CRD; Success
kubectl apply -f ./vrg-fusion25.yaml 

# Attempt to create an older style CR with the current CRD; Fails (as expected)
kubectl apply -f ./vrg-fusion24-in25.yaml 

# Update existing older style VRG to newer style; Success
kubectl apply -f ./vrg-fusion24-fixup-for-25.yaml 
kubectl get vrg -A -o yaml
```

YAML file contents:
- vrg-fusion24.yaml
```
apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: fusion-24
spec:
  async:
    mode: Disabled
    replicationClassSelector: {}
    schedulingInterval: 365d
    volumeSnapshotClassSelector: {}
  pvcSelector: {}
  replicationState: primary
  s3Profiles:
    - site1
    - site2
  sync:
    mode: Enabled
  volSync:
    disabled: true
```

- vrg-fusion24-fixup-for-25.yaml
```
apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: fusion-24
spec:
  pvcSelector: {}
  replicationState: primary
  s3Profiles:
    - site1
    - site2
  sync: {}
  volSync:
    disabled: true
```

- vrg-fusion24-in25.yaml
```
apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: fusion-24-in25
spec:
  async:
    mode: Disabled
    replicationClassSelector: {}
    schedulingInterval: 365d
    volumeSnapshotClassSelector: {}
  pvcSelector: {}
  replicationState: primary
  s3Profiles:
    - site1
    - site2
  sync:
    mode: Enabled
  volSync:
    disabled: true
```

- vrg-fusion25.yaml
```
apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: fusion-25
spec:
  pvcSelector: {}
  replicationState: primary
  s3Profiles:
    - site1
    - site2
  sync: {}
  volSync:
    disabled: true
```
