### ISSUE TITLE
Use separate storage class for minio

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#737]
Currently we use rook-ceph-block storage class for minio. This introcudce a depenency
on rook, which makes the deployment more complicated and slower.

The dependency comes from minio/minio.yaml:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio
  name: minio-config-pvc
  labels:
    component: minio
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "rook-ceph-block"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio
  name: minio-storage-pvc
  labels:
    component: minio
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "rook-ceph-block"                                                                                   
  resources:
    requests:
      storage: 10Gi

```

So in regional-dr.yaml we must install minio last:
```
      - scripts:
          - name: cert-manager
          - name: rook-operator
          - name: rook-cluster
          - name: rook-pool
          - name: rook-toolbox
          - name: minio
```

If we can use other storage, we can install minio in parallel with rook.

Since in a real system we are not using this kind of configuration, this
complexiy is unneeded.
