### ISSUE TITLE
[drenv] ManagedCluster resource on the hub should be labelled with `name: <managed cluster name>' for certain PlacementRule reconciliation 

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#757]
PlacementRule with just spec.clusters, decides which clusters to add to the placement decision based on ManagedCluster resource label: `name: <managed cluster name>`. If this is missing, a Ramen hub operation to transfer S3 secrets via a policy to the managed clusters would fail (as would volsync secrets), as its placement rule selects clusters directly.

E.g in the bash scripts this is done [here](https://github.com/RamenDR/ramen/blob/491fb9faa79f77b792754ce134438aa212f4600a/hack/ocm-minikube.sh#L638)

Sample PlacementRule that will fail to reconcile with any cluster status:
```
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: plrule-sample
spec:
  clusters:
  - name: dr1
  - name: dr2
```
