### ISSUE TITLE
docs: Configuring Ramen

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#777]
Document how to configure the ramen-operator after deployment.

drenv creates a minio instance, the secret and end point to access this s3 end point needs to be further configured once Ramen is installed

## Created ramen s3 secret

Create ramen s3 secret in the same namespace as ramen, with the s3 secret data in it ([example](https://github.com/RamenDR/ramen/blob/491fb9faa79f77b792754ce134438aa212f4600a/hack/ocm-minikube-ramen.sh#L437))

## Update ramen config map

Ramen config map needs to be updated with the s3 endpoint and reference the above secret

- Alt 1: [example](https://github.com/RamenDR/ramen/blob/491fb9faa79f77b792754ce134438aa212f4600a/hack/ocm-minikube-ramen.sh#L496)

- Alt 2: append per-cluster the following s3 details to the ramen-hub-operator-config
  ```
  s3StoreProfiles:
  - s3ProfileName: s3-on-<cluster_name>
  s3Bucket: bucket
  # drenv: minikube --profile <cluster_name> -n minio service --url minio
  s3CompatibleEndpoint: <s3 url on <cluster_name>>
  s3Region: <fake value>
  s3SecretRef:
  name: s3secret
  namespace: ramen-system
  ```

## Questions
- How is this handled downstream?
- If documented downstream, link to the docs
- Can it be automated via ramen krew plugin?
- Anything special to the test environment vs real environment?

Extracted from #760
