### ISSUE TITLE
Fail early if drenv environment file contains invalid script spec

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#809]
Recently a developer wasted lot of time because the env file contains a typo:

```
    workers:
      - scripts:
          - name: ocm-hub
          - name: ocm-controllier  <<<< 
      - scripts:
          - name: cert-manager
```

drenv skipped silently `ocm-controllier/start`, `ocm-controllier/test`, and
`ocm-controllier/stop` because they do not exit. ocm-controller was not deployed,
and turns out that without deploying it, the work-manager addon fail to deploy
in a very confusing way (clusterdm succeeds, the deployments never created).
The developer spent lot of time trying to understand why work-manager addon
was not deployed and missed the typo in ocm-controllier.

Ideally drenv should fail to load such file, but this will break the unit tests using
a file with non-existing script. This is also not enough, since a script may exist when
the file is loaded, and deleted renamed few minutes after the starting, for example during
development. So we really need to both validate the env file properly when loading it, and
warn about missing scripts at the time we run the script.

Tasks:
- [ ] Warn if a script directory does not exist when running a script
- [ ] Fix the unit tests so they do not reference missing scripts
- [ ] Validate that script exists when validating scripts in envfile.py, so loading will fail.
