### ISSUE TITLE
OLM was unable to show ramen operator when host OS arch is other than amd64  

### ISSUE THREAD

**Issue by rakeshgm** [RamenDR/ramen#823]
A few of the labels were missing in the CSV files.

```
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
```
