### ISSUE TITLE
Recipe Hooks: success criteria should include finding valid pod, backed up items

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#897]
## Background
Recipe success/failure detection for individual backups in a sequence is based upon a Backup `status.phase` result. When a Backup is successful, `status.phase=Completed`.

When a Hook runs in Velero, it must be executed on a running Pod. Currently, Ramen requires that a user ensures that valid Pods exist before attempting to run a Hook during a Backup/Recovery Sequence.

## Issue Found
When running a Backup that executes a Hook, and the Pod that should run the Hook is not found, Velero will return a `Completed` status, despite not doing any work. Impact on Ramen: if a user runs a Hook as the first step of a Recipe Recovery sequence (before Pods have been restored), or has not restored the Pod required for use with the Hook, the Hook behavior will be skipped and not return an error. Backup Hooks are also skipped in the same manner.

Discovered during testing of PR #874.

### Without Ramen
1. Install Velero on OCP or Minikube cluster.
1. Create Backup object that should run a Hook, but don't create the Pod it would run on.
1. Wait for Backup to finish. Observe `status.phase=Completed` and `status.progress.itemsBackedUp=0`.

An example YAML file for reproducing this is below.

#### During Recovery Sequence
1. Install Ramen on OCP or Minikube.
1. Launch an app and add DR protection with Ramen.
1. Create a Recipe that uses a Hook as the first step of the Recovery sequence.
1. Perform a Failover, then observe the results when Kube Objects are Restored.

**Expected results**: since the Hook cannot be run, it should fail and be retried in place. The user should either update the Recipe, or manually run the Pod to correct this.
**Actual results**: Hook is "successful" and the next step in the Recovery sequence will run.

#### During Capture Sequence
1. Install Ramen on OCP or Minikube.
1. Launch an app and add DR protection with Ramen.
1. Create a Recipe for a Pod or Container that does not exist in the Namespace.
1. Run a Capture sequence and observe the results.

**Expected results**: the Hook should fail since the Pod/Container does not exist.
**Actual results**: the Hook is "successful" and the Recipe will progress to the next step in the Capture sequence.

## Proposed Solution
In addition to checking `status.phase`, also check `status.progress.itemsBackedUp`, which should return a positive result. If zero items have been backed up and `status.phase=Completed`, then consider the Hook a failure and retry it.

## Sample Backup Showing the Issue
Below is a `backup.velero.io` sample used to demonstrate this issue on Velero 1.9.3 via OADP ("standard" Velero shows the same behavior on Minikube). 
```yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup-debug-recipe-test
  namespace: openshift-adp
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToRestic: false
  hooks:
    resources:
    - labelSelector:
        matchLabels:
          appname: busybox
      name: my-hook-test
      pre:
      - exec:
          command:
          - /bin/sh
          - c
          - rm /tmp/a || ! touch /tmp/a
          timeout: 5m
  includedNamespaces:
  - recipe-test
  includedResources:
  - pods  # note: no pods were running in recipe-test NS at the time
  metadata: {}
  snapshotVolumes: false
  storageLocation: velero-sample-1
  ttl: 720h0m0s
status:
  completionTimestamp: "2023-05-26T00:39:56Z"
  expiration: "2023-06-25T00:38:27Z"
  formatVersion: 1.1.0
  phase: Completed  # expected to show Failed or PartiallyFailed
  progress:
    itemsBackedUp: 0  # no items were backed up, so Hook did not run
    totalItems: 0
  startTimestamp: "2023-05-26T00:38:27Z"
  version: 1
```
